export const DEFAULT_SOURCE_ROOT = '/Users/abiolalimitless/gameidea/Kenney Game Assets All-in-1 3';

export const WAVE1_PACKS = [
  {
    lane: 'endless_flyer',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'Tappy Plane',
    role: 'core',
  },
  {
    lane: 'endless_flyer',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'Jumper Pack',
    role: 'support',
  },
  {
    lane: 'endless_flyer',
    runtime: 'ui',
    section: 'UI assets',
    packName: 'Mobile Controls',
    role: 'controls',
  },
  {
    lane: 'endless_flyer',
    runtime: 'ui',
    section: 'UI assets',
    packName: 'UI Pack',
    role: 'ui',
  },
  {
    lane: 'endless_flyer',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'Particle Pack',
    role: 'fx',
  },
  {
    lane: 'endless_flyer',
    runtime: 'audio',
    section: 'Audio',
    packName: 'Music Jingles',
    role: 'music',
  },
  {
    lane: 'endless_flyer',
    runtime: 'audio',
    section: 'Audio',
    packName: 'Interface Sounds',
    role: 'sfx',
  },
  {
    lane: 'topdown_arcade',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'Topdown Shooter',
    role: 'core',
  },
  {
    lane: 'topdown_arcade',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'Desert Shooter Pack',
    role: 'support',
  },
  {
    lane: 'topdown_arcade',
    runtime: 'ui',
    section: 'UI assets',
    packName: 'Mobile Controls',
    role: 'controls',
  },
  {
    lane: 'topdown_arcade',
    runtime: 'ui',
    section: 'UI assets',
    packName: 'UI Pack - Sci-fi',
    role: 'ui',
  },
  {
    lane: 'topdown_arcade',
    runtime: 'audio',
    section: 'Audio',
    packName: 'Impact Sounds',
    role: 'sfx',
  },
  {
    lane: 'topdown_arcade',
    runtime: 'audio',
    section: 'Audio',
    packName: 'Interface Sounds',
    role: 'sfx',
  },
  {
    lane: 'pixel_platformer',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'New Platformer Pack',
    role: 'core',
  },
  {
    lane: 'pixel_platformer',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'Platformer Assets Pixel',
    role: 'support',
  },
  {
    lane: 'pixel_platformer',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'Platformer Assets Base',
    role: 'support',
  },
  {
    lane: 'pixel_platformer',
    runtime: 'ui',
    section: 'UI assets',
    packName: 'UI Pack - Pixel Adventure',
    role: 'ui',
  },
  {
    lane: 'pixel_platformer',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'Particle Pack',
    role: 'fx',
  },
  {
    lane: 'pixel_platformer',
    runtime: 'audio',
    section: 'Audio',
    packName: 'Music Jingles',
    role: 'music',
  },
  {
    lane: 'auto_battler_arena',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'Tiny Battle',
    role: 'core',
  },
  {
    lane: 'auto_battler_arena',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'RTS Medieval (Pixel)',
    role: 'support',
  },
  {
    lane: 'auto_battler_arena',
    runtime: 'canvas2d',
    section: '2D assets',
    packName: 'Tower Defense',
    role: 'support',
  },
  {
    lane: 'auto_battler_arena',
    runtime: 'ui',
    section: 'UI assets',
    packName: 'Fantasy UI Borders',
    role: 'ui',
  },
  {
    lane: 'auto_battler_arena',
    runtime: 'audio',
    section: 'Audio',
    packName: 'Impact Sounds',
    role: 'sfx',
  },
  {
    lane: 'auto_battler_arena',
    runtime: 'audio',
    section: 'Audio',
    packName: 'Music Loops',
    role: 'music',
  },
  {
    lane: 'first_person_threejs',
    runtime: 'threejs',
    section: '3D assets',
    packName: 'Mini Dungeon',
    role: 'core',
  },
  {
    lane: 'first_person_threejs',
    runtime: 'threejs',
    section: '3D assets',
    packName: 'Graveyard Kit',
    role: 'support',
  },
  {
    lane: 'first_person_threejs',
    runtime: 'threejs',
    section: '3D assets',
    packName: 'Survival Kit',
    role: 'support',
  },
  {
    lane: 'first_person_threejs',
    runtime: 'threejs',
    section: '3D assets',
    packName: 'Weapon Pack',
    role: 'weapons',
  },
  {
    lane: 'first_person_threejs',
    runtime: 'ui',
    section: 'UI assets',
    packName: 'Mobile Controls',
    role: 'controls',
  },
  {
    lane: 'first_person_threejs',
    runtime: 'audio',
    section: 'Audio',
    packName: 'Impact Sounds',
    role: 'sfx',
  },
  {
    lane: 'first_person_threejs',
    runtime: 'audio',
    section: 'Audio',
    packName: 'Interface Sounds',
    role: 'sfx',
  },
];

export const RUNTIME_EXTENSIONS = {
  canvas2d: new Set(['.png', '.jpg', '.jpeg', '.webp']),
  ui: new Set(['.png', '.jpg', '.jpeg', '.webp', '.svg']),
  audio: new Set(['.wav', '.mp3', '.ogg', '.m4a']),
  threejs: new Set(['.glb', '.png', '.jpg', '.jpeg', '.webp']),
};
